### ISSUE TITLE
Limit playlist queuing to 10 videos

### ISSUE THREAD

**Issue by tristantech** [celskeggs/musicazooing#18]
Users are queuing hundreds of videos at once, making it very difficult to queue legitimate songs. Large playlists also have the potential to strain the cache and can lead to throttling by Youtube.

**Comment by sdukhovni** [comment]
This is a good idea, but I'd prefer to have the maximum playlist length as a configurable value rather than a hard-coded constant. I also think 20 would be a better default; there are lots of album playlists that have more than 10 songs, but much fewer have more than 20.

**Comment by celskeggs** [comment]
Solved in 94f0220. It's been fixed for a while but I forgot to close the issue.
